
/**
 * Generated by Babylon.js Editor
 */
export const scriptsMap = {
    "scripts/keyActions.ts": require("@/scripts/keyActions"),
	"scripts/farmer.ts": require("@/scripts/farmer"),
	"scripts/box.ts": require("@/scripts/box"),
	"scripts/beach.ts": require("@/scripts/beach")
};
