
/**
 * Generated by Babylon.js Editor
 */
export const scriptsMap = {
    "scripts/keyActions.ts": require("@/scripts/keyActions"),
	"scripts/farmerControlled.ts": require("@/scripts/farmerControlled"),
	"scripts/beach.ts": require("@/scripts/beach"),
	"scripts/box.ts": require("@/scripts/box")
};
